### ISSUE TITLE
Consider adding configuration for Docker?

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/craft#5]
This is not really an issue, more of a discussion. 

Would adding a `Dockerfile` or `docker-compose.yml` be an option/pull request that would be considered? Meaning that if a `docker-compose.yml` file, that contained an official PHP, MySQL and Postgres configuration, were to be added to this repository - would this be worth it to anyone?

Even if the end result is that the developer/project/installer decides not to use Docker, it would be a painless addition and take a minimal amount of effort to remove from their installation.

A quick example, not tested at all, would be a `docker-compose.yml` file that looks something like this:

```
version: '2'
services:

    craftcms:
        image: php/7.0-apache
        ports:
            - "80:80"
        depends_on:
            - mysql-server
        links:
            - mysql-server
        volumes:
            - ".:/var/www"
        env_file: .env

    mysql-server:
        image: mysql/5.7
        ports:
            - "3306:3306"
        volumes:
            - "./storage/database:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: SuperLongPassword!
            MYSQL_DATABASE: dev_craftcms
            MYSQL_PASSWORD: Password1!
            MYSQL_USER: craftcms
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
```
